// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "public"."users" (
  "name", "email", "password_hash", "promptpay_id", "promptpay_qr"
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING user_id, name, email, password_hash, promptpay_id, promptpay_qr, created_at
`

type CreateUserParams struct {
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	PromptpayID  pgtype.Text `json:"promptpay_id"`
	PromptpayQr  pgtype.Text `json:"promptpay_qr"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.PromptpayID,
		arg.PromptpayQr,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.PromptpayID,
		&i.PromptpayQr,
		&i.CreatedAt,
	)
	return i, err
}
