// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_users.sql

package sqlc

import (
	"context"
)

const getUsers = `-- name: GetUsers :many
SELECT user_id, name, email, password_hash, promptpay_id, promptpay_qr, created_at FROM "public"."users"
ORDER BY "name"
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.PromptpayID,
			&i.PromptpayQr,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
