// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_user.sql

package sqlc

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT user_id, name, email, password_hash, promptpay_id, promptpay_qr, created_at FROM "public"."users"
WHERE "user_id" = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.PromptpayID,
		&i.PromptpayQr,
		&i.CreatedAt,
	)
	return i, err
}
