// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ExpenseID   int64            `json:"expense_id"`
	GroupID     pgtype.Int8      `json:"group_id"`
	Title       string           `json:"title"`
	TotalAmount pgtype.Numeric   `json:"total_amount"`
	PayerID     pgtype.Int8      `json:"payer_id"`
	ExpenseType int32            `json:"expense_type"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type ExpenseShare struct {
	ShareID   int64          `json:"share_id"`
	ExpenseID pgtype.Int8    `json:"expense_id"`
	UserID    pgtype.Int8    `json:"user_id"`
	Amount    pgtype.Numeric `json:"amount"`
}

type Group struct {
	GroupID   int64            `json:"group_id"`
	GroupName string           `json:"group_name"`
	OwnerID   pgtype.Int8      `json:"owner_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type GroupMember struct {
	ID       int64            `json:"id"`
	GroupID  pgtype.Int8      `json:"group_id"`
	UserID   pgtype.Int8      `json:"user_id"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}

type InstallmentPayment struct {
	PaymentID int64            `json:"payment_id"`
	PlanID    pgtype.Int8      `json:"plan_id"`
	MonthNo   int32            `json:"month_no"`
	DueDate   pgtype.Date      `json:"due_date"`
	Amount    pgtype.Numeric   `json:"amount"`
	State     pgtype.Int4      `json:"state"`
	PaidDate  pgtype.Timestamp `json:"paid_date"`
}

type InstallmentPlan struct {
	PlanID        int64          `json:"plan_id"`
	ExpenseID     pgtype.Int8    `json:"expense_id"`
	DebtorID      pgtype.Int8    `json:"debtor_id"`
	TotalMonths   int32          `json:"total_months"`
	MonthlyAmount pgtype.Numeric `json:"monthly_amount"`
	StartDate     pgtype.Date    `json:"start_date"`
	State         pgtype.Int4    `json:"state"`
}

type Payment struct {
	PaymentID            int64            `json:"payment_id"`
	FromUserID           pgtype.Int8      `json:"from_user_id"`
	ToUserID             pgtype.Int8      `json:"to_user_id"`
	ExpenseID            pgtype.Int8      `json:"expense_id"`
	InstallmentPaymentID pgtype.Int8      `json:"installment_payment_id"`
	Amount               pgtype.Numeric   `json:"amount"`
	State                pgtype.Int4      `json:"state"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
}

type User struct {
	UserID       int64            `json:"user_id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	PromptpayID  pgtype.Text      `json:"promptpay_id"`
	PromptpayQr  pgtype.Text      `json:"promptpay_qr"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
