// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateUser = `-- name: UpdateUser :one
UPDATE "public"."users"
  set "name" = $2,
  "email" = $3,
  "password_hash" = $4,
  "promptpay_id" = $5,
  "promptpay_qr" = $6
WHERE "user_id" = $1
RETURNING user_id, name, email, password_hash, promptpay_id, promptpay_qr, created_at
`

type UpdateUserParams struct {
	UserID       int64       `json:"user_id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	PromptpayID  pgtype.Text `json:"promptpay_id"`
	PromptpayQr  pgtype.Text `json:"promptpay_qr"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.PromptpayID,
		arg.PromptpayQr,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.PromptpayID,
		&i.PromptpayQr,
		&i.CreatedAt,
	)
	return i, err
}
